# Clippy configuration
# Allow some lints that are too strict for this project
allow = [
    "clippy::too_many_arguments",
    "clippy::needless_pass_by_value",
    "clippy::missing_errors_doc",
    "clippy::missing_panics_doc",
]

# Deny some important lints
deny = [
    "clippy::unwrap_used",
    "clippy::expect_used",
    "clippy::panic",
    "clippy::todo",
    "clippy::unimplemented",
    "clippy::unreachable",
]
