repos:
  # Rust formatting and linting
  - repo: https://github.com/rust-lang/rustfmt
    rev: stable
    hooks:
      - id: rustfmt
        args: [--edition, 2021]
  
  - repo: https://github.com/rust-lang/rust-clippy
    rev: stable
    hooks:
      - id: clippy
        args: [--all-targets, --all-features, -- -D warnings]

  # Conventional commits validation
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.4.0
    hooks:
      - id: conventional-pre-commit
        args: [--types, feat,fix,docs,style,refactor,perf,test,chore,ci,build,revert]
        stages: [commit-msg]

  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict
      - id: check-added-large-files
        args: [--maxkb=1000]
      - id: check-case-conflict
      - id: check-json
      - id: pretty-format-json
        args: [--autofix]
      - id: check-merge-conflict
      - id: debug-statements
      - id: detect-private-key

  # Cargo checks
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: cargo-check
      - id: cargo-fmt
      - id: cargo-clippy
        args: [--all-targets, --all-features, -- -D warnings]
      - id: cargo-test
